FROM node:18.12.1 AS builder

COPY ./package.json ./package.json
RUN npm install

COPY . .
RUN npm run build

FROM node:18.12.1-alpine AS frontend

COPY ./package.json ./package.json
RUN npm install --production

COPY --from=builder ./build/ ./build/
# CMD npm rum start:pord
RUN npm install -g serve

CMD serve -s build -l 3000
