FROM node:18.12.1 AS builder

COPY ./package.json ./package.json

RUN npm install

COPY . .

ARG REACT_APP_API_URL
ENV REACT_APP_API_URL $REACT_APP_API_URL

ARG REACT_APP_OMISE_PUBLIC_KEY
ENV REACT_APP_OMISE_PUBLIC_KEY $REACT_APP_OMISE_PUBLIC_KEY

RUN npm run build


FROM node:18.15-alpine AS frontend

RUN npm install -g serve
COPY --from=builder ./build/ ./build/

CMD serve -s build -l 3000



