// Code generated by ent, DO NOT EDIT.

package payment

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/2110336-2565-2/Sec3-Group16-Tuder/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Payment {
	return predicate.Payment(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Payment {
	return predicate.Payment(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Payment {
	return predicate.Payment(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Payment {
	return predicate.Payment(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Payment {
	return predicate.Payment(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Payment {
	return predicate.Payment(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Payment {
	return predicate.Payment(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Payment {
	return predicate.Payment(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Payment {
	return predicate.Payment(sql.FieldLTE(FieldID, id))
}

// QrPictureURL applies equality check predicate on the "qr_picture_url" field. It's identical to QrPictureURLEQ.
func QrPictureURL(v string) predicate.Payment {
	return predicate.Payment(sql.FieldEQ(FieldQrPictureURL, v))
}

// QrPictureURLEQ applies the EQ predicate on the "qr_picture_url" field.
func QrPictureURLEQ(v string) predicate.Payment {
	return predicate.Payment(sql.FieldEQ(FieldQrPictureURL, v))
}

// QrPictureURLNEQ applies the NEQ predicate on the "qr_picture_url" field.
func QrPictureURLNEQ(v string) predicate.Payment {
	return predicate.Payment(sql.FieldNEQ(FieldQrPictureURL, v))
}

// QrPictureURLIn applies the In predicate on the "qr_picture_url" field.
func QrPictureURLIn(vs ...string) predicate.Payment {
	return predicate.Payment(sql.FieldIn(FieldQrPictureURL, vs...))
}

// QrPictureURLNotIn applies the NotIn predicate on the "qr_picture_url" field.
func QrPictureURLNotIn(vs ...string) predicate.Payment {
	return predicate.Payment(sql.FieldNotIn(FieldQrPictureURL, vs...))
}

// QrPictureURLGT applies the GT predicate on the "qr_picture_url" field.
func QrPictureURLGT(v string) predicate.Payment {
	return predicate.Payment(sql.FieldGT(FieldQrPictureURL, v))
}

// QrPictureURLGTE applies the GTE predicate on the "qr_picture_url" field.
func QrPictureURLGTE(v string) predicate.Payment {
	return predicate.Payment(sql.FieldGTE(FieldQrPictureURL, v))
}

// QrPictureURLLT applies the LT predicate on the "qr_picture_url" field.
func QrPictureURLLT(v string) predicate.Payment {
	return predicate.Payment(sql.FieldLT(FieldQrPictureURL, v))
}

// QrPictureURLLTE applies the LTE predicate on the "qr_picture_url" field.
func QrPictureURLLTE(v string) predicate.Payment {
	return predicate.Payment(sql.FieldLTE(FieldQrPictureURL, v))
}

// QrPictureURLContains applies the Contains predicate on the "qr_picture_url" field.
func QrPictureURLContains(v string) predicate.Payment {
	return predicate.Payment(sql.FieldContains(FieldQrPictureURL, v))
}

// QrPictureURLHasPrefix applies the HasPrefix predicate on the "qr_picture_url" field.
func QrPictureURLHasPrefix(v string) predicate.Payment {
	return predicate.Payment(sql.FieldHasPrefix(FieldQrPictureURL, v))
}

// QrPictureURLHasSuffix applies the HasSuffix predicate on the "qr_picture_url" field.
func QrPictureURLHasSuffix(v string) predicate.Payment {
	return predicate.Payment(sql.FieldHasSuffix(FieldQrPictureURL, v))
}

// QrPictureURLIsNil applies the IsNil predicate on the "qr_picture_url" field.
func QrPictureURLIsNil() predicate.Payment {
	return predicate.Payment(sql.FieldIsNull(FieldQrPictureURL))
}

// QrPictureURLNotNil applies the NotNil predicate on the "qr_picture_url" field.
func QrPictureURLNotNil() predicate.Payment {
	return predicate.Payment(sql.FieldNotNull(FieldQrPictureURL))
}

// QrPictureURLEqualFold applies the EqualFold predicate on the "qr_picture_url" field.
func QrPictureURLEqualFold(v string) predicate.Payment {
	return predicate.Payment(sql.FieldEqualFold(FieldQrPictureURL, v))
}

// QrPictureURLContainsFold applies the ContainsFold predicate on the "qr_picture_url" field.
func QrPictureURLContainsFold(v string) predicate.Payment {
	return predicate.Payment(sql.FieldContainsFold(FieldQrPictureURL, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.Payment {
	return predicate.Payment(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.Payment {
	return predicate.Payment(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(UserInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasPaymentHistory applies the HasEdge predicate on the "payment_history" edge.
func HasPaymentHistory() predicate.Payment {
	return predicate.Payment(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, PaymentHistoryTable, PaymentHistoryColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPaymentHistoryWith applies the HasEdge predicate on the "payment_history" edge with a given conditions (other predicates).
func HasPaymentHistoryWith(preds ...predicate.PaymentHistory) predicate.Payment {
	return predicate.Payment(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(PaymentHistoryInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, PaymentHistoryTable, PaymentHistoryColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Payment) predicate.Payment {
	return predicate.Payment(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Payment) predicate.Payment {
	return predicate.Payment(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Payment) predicate.Payment {
	return predicate.Payment(func(s *sql.Selector) {
		p(s.Not())
	})
}
