version: '3.7'

networks:
  tuder: {}

services:
  database:
    image: postgres:15
    restart: always 
    volumes:
      - database-storage:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tuder
      POSTGRES_USER: user
    ports:
      - 5432:5432
    networks:
      - tuder

  frontend:
    build: ./Frontend
    image: champkub6/tuder-frontend
    restart: always
    ports:
      - 3000:${PORT}
    depends_on:
      - backend
    # env_file:
    #   - .env
    environment:
      PORT: ${PORT}
      REACT_APP_API_URL: ${REACT_APP_API_URL}
      REACT_APP_OMISE_PUBLIC_KEY: ${REACT_APP_OMISE_PUBLIC_KEY}
    networks:
      - tuder


  backend:
    build: ./Backend
    image: champkub6/tuder-backend
    restart: always
    ports:
      - 8080:${SERVER_PORT}
    depends_on:
      - database
    # env_file:
    #   - .env
    environment:
      MODE: ${MODE}
      SERVER_PORT: ${SERVER_PORT}
      SERVER_HOST: ${SERVER_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_MINUTES: ${JWT_EXPIRES_MINUTES}
      FRONTEND_URL: ${FRONTEND_URL}
      AWS_REGION: ${AWS_REGION}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      OMISE_PUBLIC_KEY: ${OMISE_PUBLIC_KEY}
      OMISE_SECRET_KEY: ${OMISE_SECRET_KEY}
    
    networks:
      - tuder

    

volumes:
  database-storage: