package datas

import (
	"context"
	"log"
	"fmt"
	"github.com/2110336-2565-2/Sec3-Group16-Tuder/ent"
	Course "github.com/2110336-2565-2/Sec3-Group16-Tuder/ent/course"
	"github.com/google/uuid"
)


func InsertCourse(
	client *ent.Client,
	ctx context.Context,
	tutor *ent.Tutor,
	title string,
	subject string,
	topic string,
	estimatedTime int,
	description string,
	pricePerHour int,
	level Course.Level,
	coursePictureURL string,
) (*ent.Course) {

	// Generate a new UUID for the course.
	courseId := uuid.New()

	// Does not require to check if the course already exists.
	// Because the course ID is generated by the system.
	// There is no index that is related to the other fields.

	// Create a new course.
	course, err := client.Course.Create().
		SetID(courseId).
		SetTutorID(tutor.ID).
		SetTitle(title).
		SetSubject(subject).
		SetTopic(topic).
		SetEstimatedTime(estimatedTime).
		SetDescription(description).
		SetPricePerHour(pricePerHour).
		SetLevel(level).
		SetCoursePictureURL(coursePictureURL).
		Save(ctx)

	if err != nil {
		log.Fatalf("failed creating course: %v", err)
	}

	fmt.Println("Course created: ", course)

	return course
}