// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/2110336-2565-2/Sec3-Group16-Tuder/ent/classcancelrequest"
	"github.com/2110336-2565-2/Sec3-Group16-Tuder/ent/match"
	"github.com/2110336-2565-2/Sec3-Group16-Tuder/ent/user"
	"github.com/google/uuid"
)

// ClassCancelRequestCreate is the builder for creating a ClassCancelRequest entity.
type ClassCancelRequestCreate struct {
	config
	mutation *ClassCancelRequestMutation
	hooks    []Hook
}

// SetTitle sets the "title" field.
func (ccrc *ClassCancelRequestCreate) SetTitle(s string) *ClassCancelRequestCreate {
	ccrc.mutation.SetTitle(s)
	return ccrc
}

// SetReportDate sets the "report_date" field.
func (ccrc *ClassCancelRequestCreate) SetReportDate(t time.Time) *ClassCancelRequestCreate {
	ccrc.mutation.SetReportDate(t)
	return ccrc
}

// SetNillableReportDate sets the "report_date" field if the given value is not nil.
func (ccrc *ClassCancelRequestCreate) SetNillableReportDate(t *time.Time) *ClassCancelRequestCreate {
	if t != nil {
		ccrc.SetReportDate(*t)
	}
	return ccrc
}

// SetImgURL sets the "img_url" field.
func (ccrc *ClassCancelRequestCreate) SetImgURL(s string) *ClassCancelRequestCreate {
	ccrc.mutation.SetImgURL(s)
	return ccrc
}

// SetDescription sets the "description" field.
func (ccrc *ClassCancelRequestCreate) SetDescription(s string) *ClassCancelRequestCreate {
	ccrc.mutation.SetDescription(s)
	return ccrc
}

// SetStatus sets the "status" field.
func (ccrc *ClassCancelRequestCreate) SetStatus(c classcancelrequest.Status) *ClassCancelRequestCreate {
	ccrc.mutation.SetStatus(c)
	return ccrc
}

// SetID sets the "id" field.
func (ccrc *ClassCancelRequestCreate) SetID(u uuid.UUID) *ClassCancelRequestCreate {
	ccrc.mutation.SetID(u)
	return ccrc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (ccrc *ClassCancelRequestCreate) SetNillableID(u *uuid.UUID) *ClassCancelRequestCreate {
	if u != nil {
		ccrc.SetID(*u)
	}
	return ccrc
}

// SetMatchID sets the "match" edge to the Match entity by ID.
func (ccrc *ClassCancelRequestCreate) SetMatchID(id uuid.UUID) *ClassCancelRequestCreate {
	ccrc.mutation.SetMatchID(id)
	return ccrc
}

// SetMatch sets the "match" edge to the Match entity.
func (ccrc *ClassCancelRequestCreate) SetMatch(m *Match) *ClassCancelRequestCreate {
	return ccrc.SetMatchID(m.ID)
}

// SetUserID sets the "user" edge to the User entity by ID.
func (ccrc *ClassCancelRequestCreate) SetUserID(id uuid.UUID) *ClassCancelRequestCreate {
	ccrc.mutation.SetUserID(id)
	return ccrc
}

// SetUser sets the "user" edge to the User entity.
func (ccrc *ClassCancelRequestCreate) SetUser(u *User) *ClassCancelRequestCreate {
	return ccrc.SetUserID(u.ID)
}

// Mutation returns the ClassCancelRequestMutation object of the builder.
func (ccrc *ClassCancelRequestCreate) Mutation() *ClassCancelRequestMutation {
	return ccrc.mutation
}

// Save creates the ClassCancelRequest in the database.
func (ccrc *ClassCancelRequestCreate) Save(ctx context.Context) (*ClassCancelRequest, error) {
	ccrc.defaults()
	return withHooks[*ClassCancelRequest, ClassCancelRequestMutation](ctx, ccrc.sqlSave, ccrc.mutation, ccrc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (ccrc *ClassCancelRequestCreate) SaveX(ctx context.Context) *ClassCancelRequest {
	v, err := ccrc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ccrc *ClassCancelRequestCreate) Exec(ctx context.Context) error {
	_, err := ccrc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ccrc *ClassCancelRequestCreate) ExecX(ctx context.Context) {
	if err := ccrc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ccrc *ClassCancelRequestCreate) defaults() {
	if _, ok := ccrc.mutation.ReportDate(); !ok {
		v := classcancelrequest.DefaultReportDate()
		ccrc.mutation.SetReportDate(v)
	}
	if _, ok := ccrc.mutation.ID(); !ok {
		v := classcancelrequest.DefaultID()
		ccrc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ccrc *ClassCancelRequestCreate) check() error {
	if _, ok := ccrc.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "ClassCancelRequest.title"`)}
	}
	if v, ok := ccrc.mutation.Title(); ok {
		if err := classcancelrequest.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "ClassCancelRequest.title": %w`, err)}
		}
	}
	if _, ok := ccrc.mutation.ReportDate(); !ok {
		return &ValidationError{Name: "report_date", err: errors.New(`ent: missing required field "ClassCancelRequest.report_date"`)}
	}
	if _, ok := ccrc.mutation.ImgURL(); !ok {
		return &ValidationError{Name: "img_url", err: errors.New(`ent: missing required field "ClassCancelRequest.img_url"`)}
	}
	if _, ok := ccrc.mutation.Description(); !ok {
		return &ValidationError{Name: "description", err: errors.New(`ent: missing required field "ClassCancelRequest.description"`)}
	}
	if v, ok := ccrc.mutation.Description(); ok {
		if err := classcancelrequest.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "ClassCancelRequest.description": %w`, err)}
		}
	}
	if _, ok := ccrc.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "ClassCancelRequest.status"`)}
	}
	if v, ok := ccrc.mutation.Status(); ok {
		if err := classcancelrequest.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ClassCancelRequest.status": %w`, err)}
		}
	}
	if _, ok := ccrc.mutation.MatchID(); !ok {
		return &ValidationError{Name: "match", err: errors.New(`ent: missing required edge "ClassCancelRequest.match"`)}
	}
	if _, ok := ccrc.mutation.UserID(); !ok {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "ClassCancelRequest.user"`)}
	}
	return nil
}

func (ccrc *ClassCancelRequestCreate) sqlSave(ctx context.Context) (*ClassCancelRequest, error) {
	if err := ccrc.check(); err != nil {
		return nil, err
	}
	_node, _spec := ccrc.createSpec()
	if err := sqlgraph.CreateNode(ctx, ccrc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	ccrc.mutation.id = &_node.ID
	ccrc.mutation.done = true
	return _node, nil
}

func (ccrc *ClassCancelRequestCreate) createSpec() (*ClassCancelRequest, *sqlgraph.CreateSpec) {
	var (
		_node = &ClassCancelRequest{config: ccrc.config}
		_spec = sqlgraph.NewCreateSpec(classcancelrequest.Table, sqlgraph.NewFieldSpec(classcancelrequest.FieldID, field.TypeUUID))
	)
	if id, ok := ccrc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := ccrc.mutation.Title(); ok {
		_spec.SetField(classcancelrequest.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := ccrc.mutation.ReportDate(); ok {
		_spec.SetField(classcancelrequest.FieldReportDate, field.TypeTime, value)
		_node.ReportDate = value
	}
	if value, ok := ccrc.mutation.ImgURL(); ok {
		_spec.SetField(classcancelrequest.FieldImgURL, field.TypeString, value)
		_node.ImgURL = value
	}
	if value, ok := ccrc.mutation.Description(); ok {
		_spec.SetField(classcancelrequest.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := ccrc.mutation.Status(); ok {
		_spec.SetField(classcancelrequest.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if nodes := ccrc.mutation.MatchIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   classcancelrequest.MatchTable,
			Columns: []string{classcancelrequest.MatchColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: match.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.match_class_cancel_request = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := ccrc.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   classcancelrequest.UserTable,
			Columns: []string{classcancelrequest.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_class_cancel_request = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ClassCancelRequestCreateBulk is the builder for creating many ClassCancelRequest entities in bulk.
type ClassCancelRequestCreateBulk struct {
	config
	builders []*ClassCancelRequestCreate
}

// Save creates the ClassCancelRequest entities in the database.
func (ccrcb *ClassCancelRequestCreateBulk) Save(ctx context.Context) ([]*ClassCancelRequest, error) {
	specs := make([]*sqlgraph.CreateSpec, len(ccrcb.builders))
	nodes := make([]*ClassCancelRequest, len(ccrcb.builders))
	mutators := make([]Mutator, len(ccrcb.builders))
	for i := range ccrcb.builders {
		func(i int, root context.Context) {
			builder := ccrcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ClassCancelRequestMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, ccrcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, ccrcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, ccrcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (ccrcb *ClassCancelRequestCreateBulk) SaveX(ctx context.Context) []*ClassCancelRequest {
	v, err := ccrcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ccrcb *ClassCancelRequestCreateBulk) Exec(ctx context.Context) error {
	_, err := ccrcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ccrcb *ClassCancelRequestCreateBulk) ExecX(ctx context.Context) {
	if err := ccrcb.Exec(ctx); err != nil {
		panic(err)
	}
}
