// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/2110336-2565-2/Sec3-Group16-Tuder/ent/class"
	"github.com/2110336-2565-2/Sec3-Group16-Tuder/ent/course"
	"github.com/2110336-2565-2/Sec3-Group16-Tuder/ent/predicate"
	"github.com/2110336-2565-2/Sec3-Group16-Tuder/ent/schedule"
	"github.com/2110336-2565-2/Sec3-Group16-Tuder/ent/student"
	"github.com/google/uuid"
)

// ClassUpdate is the builder for updating Class entities.
type ClassUpdate struct {
	config
	hooks    []Hook
	mutation *ClassMutation
}

// Where appends a list predicates to the ClassUpdate builder.
func (cu *ClassUpdate) Where(ps ...predicate.Class) *ClassUpdate {
	cu.mutation.Where(ps...)
	return cu
}

// SetReviewAvaliable sets the "review_avaliable" field.
func (cu *ClassUpdate) SetReviewAvaliable(b bool) *ClassUpdate {
	cu.mutation.SetReviewAvaliable(b)
	return cu
}

// SetNillableReviewAvaliable sets the "review_avaliable" field if the given value is not nil.
func (cu *ClassUpdate) SetNillableReviewAvaliable(b *bool) *ClassUpdate {
	if b != nil {
		cu.SetReviewAvaliable(*b)
	}
	return cu
}

// SetTotalHour sets the "total_hour" field.
func (cu *ClassUpdate) SetTotalHour(t time.Time) *ClassUpdate {
	cu.mutation.SetTotalHour(t)
	return cu
}

// SetSuccessHour sets the "success_hour" field.
func (cu *ClassUpdate) SetSuccessHour(t time.Time) *ClassUpdate {
	cu.mutation.SetSuccessHour(t)
	return cu
}

// SetScheduleID sets the "schedule" edge to the Schedule entity by ID.
func (cu *ClassUpdate) SetScheduleID(id uuid.UUID) *ClassUpdate {
	cu.mutation.SetScheduleID(id)
	return cu
}

// SetNillableScheduleID sets the "schedule" edge to the Schedule entity by ID if the given value is not nil.
func (cu *ClassUpdate) SetNillableScheduleID(id *uuid.UUID) *ClassUpdate {
	if id != nil {
		cu = cu.SetScheduleID(*id)
	}
	return cu
}

// SetSchedule sets the "schedule" edge to the Schedule entity.
func (cu *ClassUpdate) SetSchedule(s *Schedule) *ClassUpdate {
	return cu.SetScheduleID(s.ID)
}

// SetStudentID sets the "student" edge to the Student entity by ID.
func (cu *ClassUpdate) SetStudentID(id uuid.UUID) *ClassUpdate {
	cu.mutation.SetStudentID(id)
	return cu
}

// SetStudent sets the "student" edge to the Student entity.
func (cu *ClassUpdate) SetStudent(s *Student) *ClassUpdate {
	return cu.SetStudentID(s.ID)
}

// SetCourseID sets the "course" edge to the Course entity by ID.
func (cu *ClassUpdate) SetCourseID(id uuid.UUID) *ClassUpdate {
	cu.mutation.SetCourseID(id)
	return cu
}

// SetCourse sets the "course" edge to the Course entity.
func (cu *ClassUpdate) SetCourse(c *Course) *ClassUpdate {
	return cu.SetCourseID(c.ID)
}

// Mutation returns the ClassMutation object of the builder.
func (cu *ClassUpdate) Mutation() *ClassMutation {
	return cu.mutation
}

// ClearSchedule clears the "schedule" edge to the Schedule entity.
func (cu *ClassUpdate) ClearSchedule() *ClassUpdate {
	cu.mutation.ClearSchedule()
	return cu
}

// ClearStudent clears the "student" edge to the Student entity.
func (cu *ClassUpdate) ClearStudent() *ClassUpdate {
	cu.mutation.ClearStudent()
	return cu
}

// ClearCourse clears the "course" edge to the Course entity.
func (cu *ClassUpdate) ClearCourse() *ClassUpdate {
	cu.mutation.ClearCourse()
	return cu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (cu *ClassUpdate) Save(ctx context.Context) (int, error) {
	return withHooks[int, ClassMutation](ctx, cu.sqlSave, cu.mutation, cu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (cu *ClassUpdate) SaveX(ctx context.Context) int {
	affected, err := cu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (cu *ClassUpdate) Exec(ctx context.Context) error {
	_, err := cu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cu *ClassUpdate) ExecX(ctx context.Context) {
	if err := cu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (cu *ClassUpdate) check() error {
	if _, ok := cu.mutation.StudentID(); cu.mutation.StudentCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "Class.student"`)
	}
	if _, ok := cu.mutation.CourseID(); cu.mutation.CourseCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "Class.course"`)
	}
	return nil
}

func (cu *ClassUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := cu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(class.Table, class.Columns, sqlgraph.NewFieldSpec(class.FieldID, field.TypeUUID))
	if ps := cu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cu.mutation.ReviewAvaliable(); ok {
		_spec.SetField(class.FieldReviewAvaliable, field.TypeBool, value)
	}
	if value, ok := cu.mutation.TotalHour(); ok {
		_spec.SetField(class.FieldTotalHour, field.TypeTime, value)
	}
	if value, ok := cu.mutation.SuccessHour(); ok {
		_spec.SetField(class.FieldSuccessHour, field.TypeTime, value)
	}
	if cu.mutation.ScheduleCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   class.ScheduleTable,
			Columns: []string{class.ScheduleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: schedule.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cu.mutation.ScheduleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   class.ScheduleTable,
			Columns: []string{class.ScheduleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: schedule.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if cu.mutation.StudentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   class.StudentTable,
			Columns: []string{class.StudentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: student.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cu.mutation.StudentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   class.StudentTable,
			Columns: []string{class.StudentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: student.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if cu.mutation.CourseCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   class.CourseTable,
			Columns: []string{class.CourseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: course.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cu.mutation.CourseIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   class.CourseTable,
			Columns: []string{class.CourseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: course.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, cu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{class.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	cu.mutation.done = true
	return n, nil
}

// ClassUpdateOne is the builder for updating a single Class entity.
type ClassUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ClassMutation
}

// SetReviewAvaliable sets the "review_avaliable" field.
func (cuo *ClassUpdateOne) SetReviewAvaliable(b bool) *ClassUpdateOne {
	cuo.mutation.SetReviewAvaliable(b)
	return cuo
}

// SetNillableReviewAvaliable sets the "review_avaliable" field if the given value is not nil.
func (cuo *ClassUpdateOne) SetNillableReviewAvaliable(b *bool) *ClassUpdateOne {
	if b != nil {
		cuo.SetReviewAvaliable(*b)
	}
	return cuo
}

// SetTotalHour sets the "total_hour" field.
func (cuo *ClassUpdateOne) SetTotalHour(t time.Time) *ClassUpdateOne {
	cuo.mutation.SetTotalHour(t)
	return cuo
}

// SetSuccessHour sets the "success_hour" field.
func (cuo *ClassUpdateOne) SetSuccessHour(t time.Time) *ClassUpdateOne {
	cuo.mutation.SetSuccessHour(t)
	return cuo
}

// SetScheduleID sets the "schedule" edge to the Schedule entity by ID.
func (cuo *ClassUpdateOne) SetScheduleID(id uuid.UUID) *ClassUpdateOne {
	cuo.mutation.SetScheduleID(id)
	return cuo
}

// SetNillableScheduleID sets the "schedule" edge to the Schedule entity by ID if the given value is not nil.
func (cuo *ClassUpdateOne) SetNillableScheduleID(id *uuid.UUID) *ClassUpdateOne {
	if id != nil {
		cuo = cuo.SetScheduleID(*id)
	}
	return cuo
}

// SetSchedule sets the "schedule" edge to the Schedule entity.
func (cuo *ClassUpdateOne) SetSchedule(s *Schedule) *ClassUpdateOne {
	return cuo.SetScheduleID(s.ID)
}

// SetStudentID sets the "student" edge to the Student entity by ID.
func (cuo *ClassUpdateOne) SetStudentID(id uuid.UUID) *ClassUpdateOne {
	cuo.mutation.SetStudentID(id)
	return cuo
}

// SetStudent sets the "student" edge to the Student entity.
func (cuo *ClassUpdateOne) SetStudent(s *Student) *ClassUpdateOne {
	return cuo.SetStudentID(s.ID)
}

// SetCourseID sets the "course" edge to the Course entity by ID.
func (cuo *ClassUpdateOne) SetCourseID(id uuid.UUID) *ClassUpdateOne {
	cuo.mutation.SetCourseID(id)
	return cuo
}

// SetCourse sets the "course" edge to the Course entity.
func (cuo *ClassUpdateOne) SetCourse(c *Course) *ClassUpdateOne {
	return cuo.SetCourseID(c.ID)
}

// Mutation returns the ClassMutation object of the builder.
func (cuo *ClassUpdateOne) Mutation() *ClassMutation {
	return cuo.mutation
}

// ClearSchedule clears the "schedule" edge to the Schedule entity.
func (cuo *ClassUpdateOne) ClearSchedule() *ClassUpdateOne {
	cuo.mutation.ClearSchedule()
	return cuo
}

// ClearStudent clears the "student" edge to the Student entity.
func (cuo *ClassUpdateOne) ClearStudent() *ClassUpdateOne {
	cuo.mutation.ClearStudent()
	return cuo
}

// ClearCourse clears the "course" edge to the Course entity.
func (cuo *ClassUpdateOne) ClearCourse() *ClassUpdateOne {
	cuo.mutation.ClearCourse()
	return cuo
}

// Where appends a list predicates to the ClassUpdate builder.
func (cuo *ClassUpdateOne) Where(ps ...predicate.Class) *ClassUpdateOne {
	cuo.mutation.Where(ps...)
	return cuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (cuo *ClassUpdateOne) Select(field string, fields ...string) *ClassUpdateOne {
	cuo.fields = append([]string{field}, fields...)
	return cuo
}

// Save executes the query and returns the updated Class entity.
func (cuo *ClassUpdateOne) Save(ctx context.Context) (*Class, error) {
	return withHooks[*Class, ClassMutation](ctx, cuo.sqlSave, cuo.mutation, cuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (cuo *ClassUpdateOne) SaveX(ctx context.Context) *Class {
	node, err := cuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (cuo *ClassUpdateOne) Exec(ctx context.Context) error {
	_, err := cuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cuo *ClassUpdateOne) ExecX(ctx context.Context) {
	if err := cuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (cuo *ClassUpdateOne) check() error {
	if _, ok := cuo.mutation.StudentID(); cuo.mutation.StudentCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "Class.student"`)
	}
	if _, ok := cuo.mutation.CourseID(); cuo.mutation.CourseCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "Class.course"`)
	}
	return nil
}

func (cuo *ClassUpdateOne) sqlSave(ctx context.Context) (_node *Class, err error) {
	if err := cuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(class.Table, class.Columns, sqlgraph.NewFieldSpec(class.FieldID, field.TypeUUID))
	id, ok := cuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Class.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := cuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, class.FieldID)
		for _, f := range fields {
			if !class.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != class.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := cuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cuo.mutation.ReviewAvaliable(); ok {
		_spec.SetField(class.FieldReviewAvaliable, field.TypeBool, value)
	}
	if value, ok := cuo.mutation.TotalHour(); ok {
		_spec.SetField(class.FieldTotalHour, field.TypeTime, value)
	}
	if value, ok := cuo.mutation.SuccessHour(); ok {
		_spec.SetField(class.FieldSuccessHour, field.TypeTime, value)
	}
	if cuo.mutation.ScheduleCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   class.ScheduleTable,
			Columns: []string{class.ScheduleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: schedule.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cuo.mutation.ScheduleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   class.ScheduleTable,
			Columns: []string{class.ScheduleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: schedule.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if cuo.mutation.StudentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   class.StudentTable,
			Columns: []string{class.StudentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: student.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cuo.mutation.StudentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   class.StudentTable,
			Columns: []string{class.StudentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: student.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if cuo.mutation.CourseCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   class.CourseTable,
			Columns: []string{class.CourseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: course.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cuo.mutation.CourseIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   class.CourseTable,
			Columns: []string{class.CourseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: course.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Class{config: cuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, cuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{class.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	cuo.mutation.done = true
	return _node, nil
}
