// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"

	"github.com/2110336-2565-2/Sec3-Group16-Tuder/ent/migrate"
	"github.com/google/uuid"

	"github.com/2110336-2565-2/Sec3-Group16-Tuder/ent/class"
	"github.com/2110336-2565-2/Sec3-Group16-Tuder/ent/classcancelrequest"
	"github.com/2110336-2565-2/Sec3-Group16-Tuder/ent/course"
	"github.com/2110336-2565-2/Sec3-Group16-Tuder/ent/issuereport"
	"github.com/2110336-2565-2/Sec3-Group16-Tuder/ent/match"
	"github.com/2110336-2565-2/Sec3-Group16-Tuder/ent/payment"
	"github.com/2110336-2565-2/Sec3-Group16-Tuder/ent/paymenthistory"
	"github.com/2110336-2565-2/Sec3-Group16-Tuder/ent/reviewcourse"
	"github.com/2110336-2565-2/Sec3-Group16-Tuder/ent/reviewtutor"
	"github.com/2110336-2565-2/Sec3-Group16-Tuder/ent/schedule"
	"github.com/2110336-2565-2/Sec3-Group16-Tuder/ent/student"
	"github.com/2110336-2565-2/Sec3-Group16-Tuder/ent/tutor"
	"github.com/2110336-2565-2/Sec3-Group16-Tuder/ent/user"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// Class is the client for interacting with the Class builders.
	Class *ClassClient
	// ClassCancelRequest is the client for interacting with the ClassCancelRequest builders.
	ClassCancelRequest *ClassCancelRequestClient
	// Course is the client for interacting with the Course builders.
	Course *CourseClient
	// IssueReport is the client for interacting with the IssueReport builders.
	IssueReport *IssueReportClient
	// Match is the client for interacting with the Match builders.
	Match *MatchClient
	// Payment is the client for interacting with the Payment builders.
	Payment *PaymentClient
	// PaymentHistory is the client for interacting with the PaymentHistory builders.
	PaymentHistory *PaymentHistoryClient
	// ReviewCourse is the client for interacting with the ReviewCourse builders.
	ReviewCourse *ReviewCourseClient
	// ReviewTutor is the client for interacting with the ReviewTutor builders.
	ReviewTutor *ReviewTutorClient
	// Schedule is the client for interacting with the Schedule builders.
	Schedule *ScheduleClient
	// Student is the client for interacting with the Student builders.
	Student *StudentClient
	// Tutor is the client for interacting with the Tutor builders.
	Tutor *TutorClient
	// User is the client for interacting with the User builders.
	User *UserClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	client := &Client{config: cfg}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.Class = NewClassClient(c.config)
	c.ClassCancelRequest = NewClassCancelRequestClient(c.config)
	c.Course = NewCourseClient(c.config)
	c.IssueReport = NewIssueReportClient(c.config)
	c.Match = NewMatchClient(c.config)
	c.Payment = NewPaymentClient(c.config)
	c.PaymentHistory = NewPaymentHistoryClient(c.config)
	c.ReviewCourse = NewReviewCourseClient(c.config)
	c.ReviewTutor = NewReviewTutorClient(c.config)
	c.Schedule = NewScheduleClient(c.config)
	c.Student = NewStudentClient(c.config)
	c.Tutor = NewTutorClient(c.config)
	c.User = NewUserClient(c.config)
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:                ctx,
		config:             cfg,
		Class:              NewClassClient(cfg),
		ClassCancelRequest: NewClassCancelRequestClient(cfg),
		Course:             NewCourseClient(cfg),
		IssueReport:        NewIssueReportClient(cfg),
		Match:              NewMatchClient(cfg),
		Payment:            NewPaymentClient(cfg),
		PaymentHistory:     NewPaymentHistoryClient(cfg),
		ReviewCourse:       NewReviewCourseClient(cfg),
		ReviewTutor:        NewReviewTutorClient(cfg),
		Schedule:           NewScheduleClient(cfg),
		Student:            NewStudentClient(cfg),
		Tutor:              NewTutorClient(cfg),
		User:               NewUserClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:                ctx,
		config:             cfg,
		Class:              NewClassClient(cfg),
		ClassCancelRequest: NewClassCancelRequestClient(cfg),
		Course:             NewCourseClient(cfg),
		IssueReport:        NewIssueReportClient(cfg),
		Match:              NewMatchClient(cfg),
		Payment:            NewPaymentClient(cfg),
		PaymentHistory:     NewPaymentHistoryClient(cfg),
		ReviewCourse:       NewReviewCourseClient(cfg),
		ReviewTutor:        NewReviewTutorClient(cfg),
		Schedule:           NewScheduleClient(cfg),
		Student:            NewStudentClient(cfg),
		Tutor:              NewTutorClient(cfg),
		User:               NewUserClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		Class.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.Class.Use(hooks...)
	c.ClassCancelRequest.Use(hooks...)
	c.Course.Use(hooks...)
	c.IssueReport.Use(hooks...)
	c.Match.Use(hooks...)
	c.Payment.Use(hooks...)
	c.PaymentHistory.Use(hooks...)
	c.ReviewCourse.Use(hooks...)
	c.ReviewTutor.Use(hooks...)
	c.Schedule.Use(hooks...)
	c.Student.Use(hooks...)
	c.Tutor.Use(hooks...)
	c.User.Use(hooks...)
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	c.Class.Intercept(interceptors...)
	c.ClassCancelRequest.Intercept(interceptors...)
	c.Course.Intercept(interceptors...)
	c.IssueReport.Intercept(interceptors...)
	c.Match.Intercept(interceptors...)
	c.Payment.Intercept(interceptors...)
	c.PaymentHistory.Intercept(interceptors...)
	c.ReviewCourse.Intercept(interceptors...)
	c.ReviewTutor.Intercept(interceptors...)
	c.Schedule.Intercept(interceptors...)
	c.Student.Intercept(interceptors...)
	c.Tutor.Intercept(interceptors...)
	c.User.Intercept(interceptors...)
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *ClassMutation:
		return c.Class.mutate(ctx, m)
	case *ClassCancelRequestMutation:
		return c.ClassCancelRequest.mutate(ctx, m)
	case *CourseMutation:
		return c.Course.mutate(ctx, m)
	case *IssueReportMutation:
		return c.IssueReport.mutate(ctx, m)
	case *MatchMutation:
		return c.Match.mutate(ctx, m)
	case *PaymentMutation:
		return c.Payment.mutate(ctx, m)
	case *PaymentHistoryMutation:
		return c.PaymentHistory.mutate(ctx, m)
	case *ReviewCourseMutation:
		return c.ReviewCourse.mutate(ctx, m)
	case *ReviewTutorMutation:
		return c.ReviewTutor.mutate(ctx, m)
	case *ScheduleMutation:
		return c.Schedule.mutate(ctx, m)
	case *StudentMutation:
		return c.Student.mutate(ctx, m)
	case *TutorMutation:
		return c.Tutor.mutate(ctx, m)
	case *UserMutation:
		return c.User.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// ClassClient is a client for the Class schema.
type ClassClient struct {
	config
}

// NewClassClient returns a client for the Class from the given config.
func NewClassClient(c config) *ClassClient {
	return &ClassClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `class.Hooks(f(g(h())))`.
func (c *ClassClient) Use(hooks ...Hook) {
	c.hooks.Class = append(c.hooks.Class, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `class.Intercept(f(g(h())))`.
func (c *ClassClient) Intercept(interceptors ...Interceptor) {
	c.inters.Class = append(c.inters.Class, interceptors...)
}

// Create returns a builder for creating a Class entity.
func (c *ClassClient) Create() *ClassCreate {
	mutation := newClassMutation(c.config, OpCreate)
	return &ClassCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Class entities.
func (c *ClassClient) CreateBulk(builders ...*ClassCreate) *ClassCreateBulk {
	return &ClassCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Class.
func (c *ClassClient) Update() *ClassUpdate {
	mutation := newClassMutation(c.config, OpUpdate)
	return &ClassUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ClassClient) UpdateOne(cl *Class) *ClassUpdateOne {
	mutation := newClassMutation(c.config, OpUpdateOne, withClass(cl))
	return &ClassUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ClassClient) UpdateOneID(id uuid.UUID) *ClassUpdateOne {
	mutation := newClassMutation(c.config, OpUpdateOne, withClassID(id))
	return &ClassUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Class.
func (c *ClassClient) Delete() *ClassDelete {
	mutation := newClassMutation(c.config, OpDelete)
	return &ClassDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ClassClient) DeleteOne(cl *Class) *ClassDeleteOne {
	return c.DeleteOneID(cl.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ClassClient) DeleteOneID(id uuid.UUID) *ClassDeleteOne {
	builder := c.Delete().Where(class.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ClassDeleteOne{builder}
}

// Query returns a query builder for Class.
func (c *ClassClient) Query() *ClassQuery {
	return &ClassQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeClass},
		inters: c.Interceptors(),
	}
}

// Get returns a Class entity by its id.
func (c *ClassClient) Get(ctx context.Context, id uuid.UUID) (*Class, error) {
	return c.Query().Where(class.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ClassClient) GetX(ctx context.Context, id uuid.UUID) *Class {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryMatch queries the match edge of a Class.
func (c *ClassClient) QueryMatch(cl *Class) *MatchQuery {
	query := (&MatchClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := cl.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(class.Table, class.FieldID, id),
			sqlgraph.To(match.Table, match.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, class.MatchTable, class.MatchColumn),
		)
		fromV = sqlgraph.Neighbors(cl.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QuerySchedule queries the schedule edge of a Class.
func (c *ClassClient) QuerySchedule(cl *Class) *ScheduleQuery {
	query := (&ScheduleClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := cl.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(class.Table, class.FieldID, id),
			sqlgraph.To(schedule.Table, schedule.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, class.ScheduleTable, class.ScheduleColumn),
		)
		fromV = sqlgraph.Neighbors(cl.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryPaymentHistory queries the payment_history edge of a Class.
func (c *ClassClient) QueryPaymentHistory(cl *Class) *PaymentHistoryQuery {
	query := (&PaymentHistoryClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := cl.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(class.Table, class.FieldID, id),
			sqlgraph.To(paymenthistory.Table, paymenthistory.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, class.PaymentHistoryTable, class.PaymentHistoryColumn),
		)
		fromV = sqlgraph.Neighbors(cl.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *ClassClient) Hooks() []Hook {
	return c.hooks.Class
}

// Interceptors returns the client interceptors.
func (c *ClassClient) Interceptors() []Interceptor {
	return c.inters.Class
}

func (c *ClassClient) mutate(ctx context.Context, m *ClassMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ClassCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ClassUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ClassUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ClassDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Class mutation op: %q", m.Op())
	}
}

// ClassCancelRequestClient is a client for the ClassCancelRequest schema.
type ClassCancelRequestClient struct {
	config
}

// NewClassCancelRequestClient returns a client for the ClassCancelRequest from the given config.
func NewClassCancelRequestClient(c config) *ClassCancelRequestClient {
	return &ClassCancelRequestClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `classcancelrequest.Hooks(f(g(h())))`.
func (c *ClassCancelRequestClient) Use(hooks ...Hook) {
	c.hooks.ClassCancelRequest = append(c.hooks.ClassCancelRequest, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `classcancelrequest.Intercept(f(g(h())))`.
func (c *ClassCancelRequestClient) Intercept(interceptors ...Interceptor) {
	c.inters.ClassCancelRequest = append(c.inters.ClassCancelRequest, interceptors...)
}

// Create returns a builder for creating a ClassCancelRequest entity.
func (c *ClassCancelRequestClient) Create() *ClassCancelRequestCreate {
	mutation := newClassCancelRequestMutation(c.config, OpCreate)
	return &ClassCancelRequestCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of ClassCancelRequest entities.
func (c *ClassCancelRequestClient) CreateBulk(builders ...*ClassCancelRequestCreate) *ClassCancelRequestCreateBulk {
	return &ClassCancelRequestCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for ClassCancelRequest.
func (c *ClassCancelRequestClient) Update() *ClassCancelRequestUpdate {
	mutation := newClassCancelRequestMutation(c.config, OpUpdate)
	return &ClassCancelRequestUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ClassCancelRequestClient) UpdateOne(ccr *ClassCancelRequest) *ClassCancelRequestUpdateOne {
	mutation := newClassCancelRequestMutation(c.config, OpUpdateOne, withClassCancelRequest(ccr))
	return &ClassCancelRequestUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ClassCancelRequestClient) UpdateOneID(id uuid.UUID) *ClassCancelRequestUpdateOne {
	mutation := newClassCancelRequestMutation(c.config, OpUpdateOne, withClassCancelRequestID(id))
	return &ClassCancelRequestUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for ClassCancelRequest.
func (c *ClassCancelRequestClient) Delete() *ClassCancelRequestDelete {
	mutation := newClassCancelRequestMutation(c.config, OpDelete)
	return &ClassCancelRequestDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ClassCancelRequestClient) DeleteOne(ccr *ClassCancelRequest) *ClassCancelRequestDeleteOne {
	return c.DeleteOneID(ccr.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ClassCancelRequestClient) DeleteOneID(id uuid.UUID) *ClassCancelRequestDeleteOne {
	builder := c.Delete().Where(classcancelrequest.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ClassCancelRequestDeleteOne{builder}
}

// Query returns a query builder for ClassCancelRequest.
func (c *ClassCancelRequestClient) Query() *ClassCancelRequestQuery {
	return &ClassCancelRequestQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeClassCancelRequest},
		inters: c.Interceptors(),
	}
}

// Get returns a ClassCancelRequest entity by its id.
func (c *ClassCancelRequestClient) Get(ctx context.Context, id uuid.UUID) (*ClassCancelRequest, error) {
	return c.Query().Where(classcancelrequest.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ClassCancelRequestClient) GetX(ctx context.Context, id uuid.UUID) *ClassCancelRequest {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryMatch queries the match edge of a ClassCancelRequest.
func (c *ClassCancelRequestClient) QueryMatch(ccr *ClassCancelRequest) *MatchQuery {
	query := (&MatchClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := ccr.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(classcancelrequest.Table, classcancelrequest.FieldID, id),
			sqlgraph.To(match.Table, match.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, classcancelrequest.MatchTable, classcancelrequest.MatchColumn),
		)
		fromV = sqlgraph.Neighbors(ccr.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryUser queries the user edge of a ClassCancelRequest.
func (c *ClassCancelRequestClient) QueryUser(ccr *ClassCancelRequest) *UserQuery {
	query := (&UserClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := ccr.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(classcancelrequest.Table, classcancelrequest.FieldID, id),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, classcancelrequest.UserTable, classcancelrequest.UserColumn),
		)
		fromV = sqlgraph.Neighbors(ccr.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *ClassCancelRequestClient) Hooks() []Hook {
	return c.hooks.ClassCancelRequest
}

// Interceptors returns the client interceptors.
func (c *ClassCancelRequestClient) Interceptors() []Interceptor {
	return c.inters.ClassCancelRequest
}

func (c *ClassCancelRequestClient) mutate(ctx context.Context, m *ClassCancelRequestMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ClassCancelRequestCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ClassCancelRequestUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ClassCancelRequestUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ClassCancelRequestDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown ClassCancelRequest mutation op: %q", m.Op())
	}
}

// CourseClient is a client for the Course schema.
type CourseClient struct {
	config
}

// NewCourseClient returns a client for the Course from the given config.
func NewCourseClient(c config) *CourseClient {
	return &CourseClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `course.Hooks(f(g(h())))`.
func (c *CourseClient) Use(hooks ...Hook) {
	c.hooks.Course = append(c.hooks.Course, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `course.Intercept(f(g(h())))`.
func (c *CourseClient) Intercept(interceptors ...Interceptor) {
	c.inters.Course = append(c.inters.Course, interceptors...)
}

// Create returns a builder for creating a Course entity.
func (c *CourseClient) Create() *CourseCreate {
	mutation := newCourseMutation(c.config, OpCreate)
	return &CourseCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Course entities.
func (c *CourseClient) CreateBulk(builders ...*CourseCreate) *CourseCreateBulk {
	return &CourseCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Course.
func (c *CourseClient) Update() *CourseUpdate {
	mutation := newCourseMutation(c.config, OpUpdate)
	return &CourseUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *CourseClient) UpdateOne(co *Course) *CourseUpdateOne {
	mutation := newCourseMutation(c.config, OpUpdateOne, withCourse(co))
	return &CourseUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *CourseClient) UpdateOneID(id uuid.UUID) *CourseUpdateOne {
	mutation := newCourseMutation(c.config, OpUpdateOne, withCourseID(id))
	return &CourseUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Course.
func (c *CourseClient) Delete() *CourseDelete {
	mutation := newCourseMutation(c.config, OpDelete)
	return &CourseDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *CourseClient) DeleteOne(co *Course) *CourseDeleteOne {
	return c.DeleteOneID(co.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *CourseClient) DeleteOneID(id uuid.UUID) *CourseDeleteOne {
	builder := c.Delete().Where(course.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &CourseDeleteOne{builder}
}

// Query returns a query builder for Course.
func (c *CourseClient) Query() *CourseQuery {
	return &CourseQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeCourse},
		inters: c.Interceptors(),
	}
}

// Get returns a Course entity by its id.
func (c *CourseClient) Get(ctx context.Context, id uuid.UUID) (*Course, error) {
	return c.Query().Where(course.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *CourseClient) GetX(ctx context.Context, id uuid.UUID) *Course {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryReviewCourse queries the review_course edge of a Course.
func (c *CourseClient) QueryReviewCourse(co *Course) *ReviewCourseQuery {
	query := (&ReviewCourseClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := co.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(course.Table, course.FieldID, id),
			sqlgraph.To(reviewcourse.Table, reviewcourse.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, course.ReviewCourseTable, course.ReviewCoursePrimaryKey...),
		)
		fromV = sqlgraph.Neighbors(co.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryMatch queries the match edge of a Course.
func (c *CourseClient) QueryMatch(co *Course) *MatchQuery {
	query := (&MatchClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := co.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(course.Table, course.FieldID, id),
			sqlgraph.To(match.Table, match.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, course.MatchTable, course.MatchColumn),
		)
		fromV = sqlgraph.Neighbors(co.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryTutor queries the tutor edge of a Course.
func (c *CourseClient) QueryTutor(co *Course) *TutorQuery {
	query := (&TutorClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := co.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(course.Table, course.FieldID, id),
			sqlgraph.To(tutor.Table, tutor.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, course.TutorTable, course.TutorColumn),
		)
		fromV = sqlgraph.Neighbors(co.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *CourseClient) Hooks() []Hook {
	return c.hooks.Course
}

// Interceptors returns the client interceptors.
func (c *CourseClient) Interceptors() []Interceptor {
	return c.inters.Course
}

func (c *CourseClient) mutate(ctx context.Context, m *CourseMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&CourseCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&CourseUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&CourseUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&CourseDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Course mutation op: %q", m.Op())
	}
}

// IssueReportClient is a client for the IssueReport schema.
type IssueReportClient struct {
	config
}

// NewIssueReportClient returns a client for the IssueReport from the given config.
func NewIssueReportClient(c config) *IssueReportClient {
	return &IssueReportClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `issuereport.Hooks(f(g(h())))`.
func (c *IssueReportClient) Use(hooks ...Hook) {
	c.hooks.IssueReport = append(c.hooks.IssueReport, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `issuereport.Intercept(f(g(h())))`.
func (c *IssueReportClient) Intercept(interceptors ...Interceptor) {
	c.inters.IssueReport = append(c.inters.IssueReport, interceptors...)
}

// Create returns a builder for creating a IssueReport entity.
func (c *IssueReportClient) Create() *IssueReportCreate {
	mutation := newIssueReportMutation(c.config, OpCreate)
	return &IssueReportCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of IssueReport entities.
func (c *IssueReportClient) CreateBulk(builders ...*IssueReportCreate) *IssueReportCreateBulk {
	return &IssueReportCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for IssueReport.
func (c *IssueReportClient) Update() *IssueReportUpdate {
	mutation := newIssueReportMutation(c.config, OpUpdate)
	return &IssueReportUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *IssueReportClient) UpdateOne(ir *IssueReport) *IssueReportUpdateOne {
	mutation := newIssueReportMutation(c.config, OpUpdateOne, withIssueReport(ir))
	return &IssueReportUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *IssueReportClient) UpdateOneID(id uuid.UUID) *IssueReportUpdateOne {
	mutation := newIssueReportMutation(c.config, OpUpdateOne, withIssueReportID(id))
	return &IssueReportUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for IssueReport.
func (c *IssueReportClient) Delete() *IssueReportDelete {
	mutation := newIssueReportMutation(c.config, OpDelete)
	return &IssueReportDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *IssueReportClient) DeleteOne(ir *IssueReport) *IssueReportDeleteOne {
	return c.DeleteOneID(ir.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *IssueReportClient) DeleteOneID(id uuid.UUID) *IssueReportDeleteOne {
	builder := c.Delete().Where(issuereport.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &IssueReportDeleteOne{builder}
}

// Query returns a query builder for IssueReport.
func (c *IssueReportClient) Query() *IssueReportQuery {
	return &IssueReportQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeIssueReport},
		inters: c.Interceptors(),
	}
}

// Get returns a IssueReport entity by its id.
func (c *IssueReportClient) Get(ctx context.Context, id uuid.UUID) (*IssueReport, error) {
	return c.Query().Where(issuereport.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *IssueReportClient) GetX(ctx context.Context, id uuid.UUID) *IssueReport {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryUser queries the user edge of a IssueReport.
func (c *IssueReportClient) QueryUser(ir *IssueReport) *UserQuery {
	query := (&UserClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := ir.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(issuereport.Table, issuereport.FieldID, id),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, issuereport.UserTable, issuereport.UserColumn),
		)
		fromV = sqlgraph.Neighbors(ir.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *IssueReportClient) Hooks() []Hook {
	return c.hooks.IssueReport
}

// Interceptors returns the client interceptors.
func (c *IssueReportClient) Interceptors() []Interceptor {
	return c.inters.IssueReport
}

func (c *IssueReportClient) mutate(ctx context.Context, m *IssueReportMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&IssueReportCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&IssueReportUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&IssueReportUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&IssueReportDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown IssueReport mutation op: %q", m.Op())
	}
}

// MatchClient is a client for the Match schema.
type MatchClient struct {
	config
}

// NewMatchClient returns a client for the Match from the given config.
func NewMatchClient(c config) *MatchClient {
	return &MatchClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `match.Hooks(f(g(h())))`.
func (c *MatchClient) Use(hooks ...Hook) {
	c.hooks.Match = append(c.hooks.Match, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `match.Intercept(f(g(h())))`.
func (c *MatchClient) Intercept(interceptors ...Interceptor) {
	c.inters.Match = append(c.inters.Match, interceptors...)
}

// Create returns a builder for creating a Match entity.
func (c *MatchClient) Create() *MatchCreate {
	mutation := newMatchMutation(c.config, OpCreate)
	return &MatchCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Match entities.
func (c *MatchClient) CreateBulk(builders ...*MatchCreate) *MatchCreateBulk {
	return &MatchCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Match.
func (c *MatchClient) Update() *MatchUpdate {
	mutation := newMatchMutation(c.config, OpUpdate)
	return &MatchUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *MatchClient) UpdateOne(m *Match) *MatchUpdateOne {
	mutation := newMatchMutation(c.config, OpUpdateOne, withMatch(m))
	return &MatchUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *MatchClient) UpdateOneID(id uuid.UUID) *MatchUpdateOne {
	mutation := newMatchMutation(c.config, OpUpdateOne, withMatchID(id))
	return &MatchUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Match.
func (c *MatchClient) Delete() *MatchDelete {
	mutation := newMatchMutation(c.config, OpDelete)
	return &MatchDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *MatchClient) DeleteOne(m *Match) *MatchDeleteOne {
	return c.DeleteOneID(m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *MatchClient) DeleteOneID(id uuid.UUID) *MatchDeleteOne {
	builder := c.Delete().Where(match.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &MatchDeleteOne{builder}
}

// Query returns a query builder for Match.
func (c *MatchClient) Query() *MatchQuery {
	return &MatchQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeMatch},
		inters: c.Interceptors(),
	}
}

// Get returns a Match entity by its id.
func (c *MatchClient) Get(ctx context.Context, id uuid.UUID) (*Match, error) {
	return c.Query().Where(match.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *MatchClient) GetX(ctx context.Context, id uuid.UUID) *Match {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryStudent queries the student edge of a Match.
func (c *MatchClient) QueryStudent(m *Match) *StudentQuery {
	query := (&StudentClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(match.Table, match.FieldID, id),
			sqlgraph.To(student.Table, student.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, match.StudentTable, match.StudentColumn),
		)
		fromV = sqlgraph.Neighbors(m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryCourse queries the course edge of a Match.
func (c *MatchClient) QueryCourse(m *Match) *CourseQuery {
	query := (&CourseClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(match.Table, match.FieldID, id),
			sqlgraph.To(course.Table, course.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, match.CourseTable, match.CourseColumn),
		)
		fromV = sqlgraph.Neighbors(m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryClass queries the class edge of a Match.
func (c *MatchClient) QueryClass(m *Match) *ClassQuery {
	query := (&ClassClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(match.Table, match.FieldID, id),
			sqlgraph.To(class.Table, class.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, match.ClassTable, match.ClassColumn),
		)
		fromV = sqlgraph.Neighbors(m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryClassCancelRequest queries the class_cancel_request edge of a Match.
func (c *MatchClient) QueryClassCancelRequest(m *Match) *ClassCancelRequestQuery {
	query := (&ClassCancelRequestClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(match.Table, match.FieldID, id),
			sqlgraph.To(classcancelrequest.Table, classcancelrequest.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, match.ClassCancelRequestTable, match.ClassCancelRequestColumn),
		)
		fromV = sqlgraph.Neighbors(m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *MatchClient) Hooks() []Hook {
	return c.hooks.Match
}

// Interceptors returns the client interceptors.
func (c *MatchClient) Interceptors() []Interceptor {
	return c.inters.Match
}

func (c *MatchClient) mutate(ctx context.Context, m *MatchMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&MatchCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&MatchUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&MatchUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&MatchDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Match mutation op: %q", m.Op())
	}
}

// PaymentClient is a client for the Payment schema.
type PaymentClient struct {
	config
}

// NewPaymentClient returns a client for the Payment from the given config.
func NewPaymentClient(c config) *PaymentClient {
	return &PaymentClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `payment.Hooks(f(g(h())))`.
func (c *PaymentClient) Use(hooks ...Hook) {
	c.hooks.Payment = append(c.hooks.Payment, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `payment.Intercept(f(g(h())))`.
func (c *PaymentClient) Intercept(interceptors ...Interceptor) {
	c.inters.Payment = append(c.inters.Payment, interceptors...)
}

// Create returns a builder for creating a Payment entity.
func (c *PaymentClient) Create() *PaymentCreate {
	mutation := newPaymentMutation(c.config, OpCreate)
	return &PaymentCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Payment entities.
func (c *PaymentClient) CreateBulk(builders ...*PaymentCreate) *PaymentCreateBulk {
	return &PaymentCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Payment.
func (c *PaymentClient) Update() *PaymentUpdate {
	mutation := newPaymentMutation(c.config, OpUpdate)
	return &PaymentUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *PaymentClient) UpdateOne(pa *Payment) *PaymentUpdateOne {
	mutation := newPaymentMutation(c.config, OpUpdateOne, withPayment(pa))
	return &PaymentUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *PaymentClient) UpdateOneID(id uuid.UUID) *PaymentUpdateOne {
	mutation := newPaymentMutation(c.config, OpUpdateOne, withPaymentID(id))
	return &PaymentUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Payment.
func (c *PaymentClient) Delete() *PaymentDelete {
	mutation := newPaymentMutation(c.config, OpDelete)
	return &PaymentDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *PaymentClient) DeleteOne(pa *Payment) *PaymentDeleteOne {
	return c.DeleteOneID(pa.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *PaymentClient) DeleteOneID(id uuid.UUID) *PaymentDeleteOne {
	builder := c.Delete().Where(payment.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &PaymentDeleteOne{builder}
}

// Query returns a query builder for Payment.
func (c *PaymentClient) Query() *PaymentQuery {
	return &PaymentQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypePayment},
		inters: c.Interceptors(),
	}
}

// Get returns a Payment entity by its id.
func (c *PaymentClient) Get(ctx context.Context, id uuid.UUID) (*Payment, error) {
	return c.Query().Where(payment.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *PaymentClient) GetX(ctx context.Context, id uuid.UUID) *Payment {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryUser queries the user edge of a Payment.
func (c *PaymentClient) QueryUser(pa *Payment) *UserQuery {
	query := (&UserClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := pa.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(payment.Table, payment.FieldID, id),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, payment.UserTable, payment.UserColumn),
		)
		fromV = sqlgraph.Neighbors(pa.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryPaymentHistory queries the payment_history edge of a Payment.
func (c *PaymentClient) QueryPaymentHistory(pa *Payment) *PaymentHistoryQuery {
	query := (&PaymentHistoryClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := pa.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(payment.Table, payment.FieldID, id),
			sqlgraph.To(paymenthistory.Table, paymenthistory.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, payment.PaymentHistoryTable, payment.PaymentHistoryColumn),
		)
		fromV = sqlgraph.Neighbors(pa.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *PaymentClient) Hooks() []Hook {
	return c.hooks.Payment
}

// Interceptors returns the client interceptors.
func (c *PaymentClient) Interceptors() []Interceptor {
	return c.inters.Payment
}

func (c *PaymentClient) mutate(ctx context.Context, m *PaymentMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&PaymentCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&PaymentUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&PaymentUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&PaymentDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Payment mutation op: %q", m.Op())
	}
}

// PaymentHistoryClient is a client for the PaymentHistory schema.
type PaymentHistoryClient struct {
	config
}

// NewPaymentHistoryClient returns a client for the PaymentHistory from the given config.
func NewPaymentHistoryClient(c config) *PaymentHistoryClient {
	return &PaymentHistoryClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `paymenthistory.Hooks(f(g(h())))`.
func (c *PaymentHistoryClient) Use(hooks ...Hook) {
	c.hooks.PaymentHistory = append(c.hooks.PaymentHistory, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `paymenthistory.Intercept(f(g(h())))`.
func (c *PaymentHistoryClient) Intercept(interceptors ...Interceptor) {
	c.inters.PaymentHistory = append(c.inters.PaymentHistory, interceptors...)
}

// Create returns a builder for creating a PaymentHistory entity.
func (c *PaymentHistoryClient) Create() *PaymentHistoryCreate {
	mutation := newPaymentHistoryMutation(c.config, OpCreate)
	return &PaymentHistoryCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of PaymentHistory entities.
func (c *PaymentHistoryClient) CreateBulk(builders ...*PaymentHistoryCreate) *PaymentHistoryCreateBulk {
	return &PaymentHistoryCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for PaymentHistory.
func (c *PaymentHistoryClient) Update() *PaymentHistoryUpdate {
	mutation := newPaymentHistoryMutation(c.config, OpUpdate)
	return &PaymentHistoryUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *PaymentHistoryClient) UpdateOne(ph *PaymentHistory) *PaymentHistoryUpdateOne {
	mutation := newPaymentHistoryMutation(c.config, OpUpdateOne, withPaymentHistory(ph))
	return &PaymentHistoryUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *PaymentHistoryClient) UpdateOneID(id uuid.UUID) *PaymentHistoryUpdateOne {
	mutation := newPaymentHistoryMutation(c.config, OpUpdateOne, withPaymentHistoryID(id))
	return &PaymentHistoryUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for PaymentHistory.
func (c *PaymentHistoryClient) Delete() *PaymentHistoryDelete {
	mutation := newPaymentHistoryMutation(c.config, OpDelete)
	return &PaymentHistoryDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *PaymentHistoryClient) DeleteOne(ph *PaymentHistory) *PaymentHistoryDeleteOne {
	return c.DeleteOneID(ph.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *PaymentHistoryClient) DeleteOneID(id uuid.UUID) *PaymentHistoryDeleteOne {
	builder := c.Delete().Where(paymenthistory.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &PaymentHistoryDeleteOne{builder}
}

// Query returns a query builder for PaymentHistory.
func (c *PaymentHistoryClient) Query() *PaymentHistoryQuery {
	return &PaymentHistoryQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypePaymentHistory},
		inters: c.Interceptors(),
	}
}

// Get returns a PaymentHistory entity by its id.
func (c *PaymentHistoryClient) Get(ctx context.Context, id uuid.UUID) (*PaymentHistory, error) {
	return c.Query().Where(paymenthistory.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *PaymentHistoryClient) GetX(ctx context.Context, id uuid.UUID) *PaymentHistory {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryClass queries the class edge of a PaymentHistory.
func (c *PaymentHistoryClient) QueryClass(ph *PaymentHistory) *ClassQuery {
	query := (&ClassClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := ph.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(paymenthistory.Table, paymenthistory.FieldID, id),
			sqlgraph.To(class.Table, class.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, paymenthistory.ClassTable, paymenthistory.ClassColumn),
		)
		fromV = sqlgraph.Neighbors(ph.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryUser queries the user edge of a PaymentHistory.
func (c *PaymentHistoryClient) QueryUser(ph *PaymentHistory) *UserQuery {
	query := (&UserClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := ph.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(paymenthistory.Table, paymenthistory.FieldID, id),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, paymenthistory.UserTable, paymenthistory.UserColumn),
		)
		fromV = sqlgraph.Neighbors(ph.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryPayment queries the payment edge of a PaymentHistory.
func (c *PaymentHistoryClient) QueryPayment(ph *PaymentHistory) *PaymentQuery {
	query := (&PaymentClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := ph.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(paymenthistory.Table, paymenthistory.FieldID, id),
			sqlgraph.To(payment.Table, payment.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, paymenthistory.PaymentTable, paymenthistory.PaymentColumn),
		)
		fromV = sqlgraph.Neighbors(ph.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *PaymentHistoryClient) Hooks() []Hook {
	return c.hooks.PaymentHistory
}

// Interceptors returns the client interceptors.
func (c *PaymentHistoryClient) Interceptors() []Interceptor {
	return c.inters.PaymentHistory
}

func (c *PaymentHistoryClient) mutate(ctx context.Context, m *PaymentHistoryMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&PaymentHistoryCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&PaymentHistoryUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&PaymentHistoryUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&PaymentHistoryDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown PaymentHistory mutation op: %q", m.Op())
	}
}

// ReviewCourseClient is a client for the ReviewCourse schema.
type ReviewCourseClient struct {
	config
}

// NewReviewCourseClient returns a client for the ReviewCourse from the given config.
func NewReviewCourseClient(c config) *ReviewCourseClient {
	return &ReviewCourseClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `reviewcourse.Hooks(f(g(h())))`.
func (c *ReviewCourseClient) Use(hooks ...Hook) {
	c.hooks.ReviewCourse = append(c.hooks.ReviewCourse, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `reviewcourse.Intercept(f(g(h())))`.
func (c *ReviewCourseClient) Intercept(interceptors ...Interceptor) {
	c.inters.ReviewCourse = append(c.inters.ReviewCourse, interceptors...)
}

// Create returns a builder for creating a ReviewCourse entity.
func (c *ReviewCourseClient) Create() *ReviewCourseCreate {
	mutation := newReviewCourseMutation(c.config, OpCreate)
	return &ReviewCourseCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of ReviewCourse entities.
func (c *ReviewCourseClient) CreateBulk(builders ...*ReviewCourseCreate) *ReviewCourseCreateBulk {
	return &ReviewCourseCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for ReviewCourse.
func (c *ReviewCourseClient) Update() *ReviewCourseUpdate {
	mutation := newReviewCourseMutation(c.config, OpUpdate)
	return &ReviewCourseUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ReviewCourseClient) UpdateOne(rc *ReviewCourse) *ReviewCourseUpdateOne {
	mutation := newReviewCourseMutation(c.config, OpUpdateOne, withReviewCourse(rc))
	return &ReviewCourseUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ReviewCourseClient) UpdateOneID(id int) *ReviewCourseUpdateOne {
	mutation := newReviewCourseMutation(c.config, OpUpdateOne, withReviewCourseID(id))
	return &ReviewCourseUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for ReviewCourse.
func (c *ReviewCourseClient) Delete() *ReviewCourseDelete {
	mutation := newReviewCourseMutation(c.config, OpDelete)
	return &ReviewCourseDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ReviewCourseClient) DeleteOne(rc *ReviewCourse) *ReviewCourseDeleteOne {
	return c.DeleteOneID(rc.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ReviewCourseClient) DeleteOneID(id int) *ReviewCourseDeleteOne {
	builder := c.Delete().Where(reviewcourse.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ReviewCourseDeleteOne{builder}
}

// Query returns a query builder for ReviewCourse.
func (c *ReviewCourseClient) Query() *ReviewCourseQuery {
	return &ReviewCourseQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeReviewCourse},
		inters: c.Interceptors(),
	}
}

// Get returns a ReviewCourse entity by its id.
func (c *ReviewCourseClient) Get(ctx context.Context, id int) (*ReviewCourse, error) {
	return c.Query().Where(reviewcourse.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ReviewCourseClient) GetX(ctx context.Context, id int) *ReviewCourse {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryCourse queries the course edge of a ReviewCourse.
func (c *ReviewCourseClient) QueryCourse(rc *ReviewCourse) *CourseQuery {
	query := (&CourseClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := rc.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(reviewcourse.Table, reviewcourse.FieldID, id),
			sqlgraph.To(course.Table, course.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, reviewcourse.CourseTable, reviewcourse.CoursePrimaryKey...),
		)
		fromV = sqlgraph.Neighbors(rc.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryStudent queries the student edge of a ReviewCourse.
func (c *ReviewCourseClient) QueryStudent(rc *ReviewCourse) *StudentQuery {
	query := (&StudentClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := rc.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(reviewcourse.Table, reviewcourse.FieldID, id),
			sqlgraph.To(student.Table, student.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, reviewcourse.StudentTable, reviewcourse.StudentPrimaryKey...),
		)
		fromV = sqlgraph.Neighbors(rc.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *ReviewCourseClient) Hooks() []Hook {
	return c.hooks.ReviewCourse
}

// Interceptors returns the client interceptors.
func (c *ReviewCourseClient) Interceptors() []Interceptor {
	return c.inters.ReviewCourse
}

func (c *ReviewCourseClient) mutate(ctx context.Context, m *ReviewCourseMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ReviewCourseCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ReviewCourseUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ReviewCourseUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ReviewCourseDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown ReviewCourse mutation op: %q", m.Op())
	}
}

// ReviewTutorClient is a client for the ReviewTutor schema.
type ReviewTutorClient struct {
	config
}

// NewReviewTutorClient returns a client for the ReviewTutor from the given config.
func NewReviewTutorClient(c config) *ReviewTutorClient {
	return &ReviewTutorClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `reviewtutor.Hooks(f(g(h())))`.
func (c *ReviewTutorClient) Use(hooks ...Hook) {
	c.hooks.ReviewTutor = append(c.hooks.ReviewTutor, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `reviewtutor.Intercept(f(g(h())))`.
func (c *ReviewTutorClient) Intercept(interceptors ...Interceptor) {
	c.inters.ReviewTutor = append(c.inters.ReviewTutor, interceptors...)
}

// Create returns a builder for creating a ReviewTutor entity.
func (c *ReviewTutorClient) Create() *ReviewTutorCreate {
	mutation := newReviewTutorMutation(c.config, OpCreate)
	return &ReviewTutorCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of ReviewTutor entities.
func (c *ReviewTutorClient) CreateBulk(builders ...*ReviewTutorCreate) *ReviewTutorCreateBulk {
	return &ReviewTutorCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for ReviewTutor.
func (c *ReviewTutorClient) Update() *ReviewTutorUpdate {
	mutation := newReviewTutorMutation(c.config, OpUpdate)
	return &ReviewTutorUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ReviewTutorClient) UpdateOne(rt *ReviewTutor) *ReviewTutorUpdateOne {
	mutation := newReviewTutorMutation(c.config, OpUpdateOne, withReviewTutor(rt))
	return &ReviewTutorUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ReviewTutorClient) UpdateOneID(id int) *ReviewTutorUpdateOne {
	mutation := newReviewTutorMutation(c.config, OpUpdateOne, withReviewTutorID(id))
	return &ReviewTutorUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for ReviewTutor.
func (c *ReviewTutorClient) Delete() *ReviewTutorDelete {
	mutation := newReviewTutorMutation(c.config, OpDelete)
	return &ReviewTutorDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ReviewTutorClient) DeleteOne(rt *ReviewTutor) *ReviewTutorDeleteOne {
	return c.DeleteOneID(rt.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ReviewTutorClient) DeleteOneID(id int) *ReviewTutorDeleteOne {
	builder := c.Delete().Where(reviewtutor.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ReviewTutorDeleteOne{builder}
}

// Query returns a query builder for ReviewTutor.
func (c *ReviewTutorClient) Query() *ReviewTutorQuery {
	return &ReviewTutorQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeReviewTutor},
		inters: c.Interceptors(),
	}
}

// Get returns a ReviewTutor entity by its id.
func (c *ReviewTutorClient) Get(ctx context.Context, id int) (*ReviewTutor, error) {
	return c.Query().Where(reviewtutor.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ReviewTutorClient) GetX(ctx context.Context, id int) *ReviewTutor {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryTutor queries the tutor edge of a ReviewTutor.
func (c *ReviewTutorClient) QueryTutor(rt *ReviewTutor) *TutorQuery {
	query := (&TutorClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := rt.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(reviewtutor.Table, reviewtutor.FieldID, id),
			sqlgraph.To(tutor.Table, tutor.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, reviewtutor.TutorTable, reviewtutor.TutorPrimaryKey...),
		)
		fromV = sqlgraph.Neighbors(rt.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryStudent queries the student edge of a ReviewTutor.
func (c *ReviewTutorClient) QueryStudent(rt *ReviewTutor) *StudentQuery {
	query := (&StudentClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := rt.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(reviewtutor.Table, reviewtutor.FieldID, id),
			sqlgraph.To(student.Table, student.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, reviewtutor.StudentTable, reviewtutor.StudentPrimaryKey...),
		)
		fromV = sqlgraph.Neighbors(rt.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *ReviewTutorClient) Hooks() []Hook {
	return c.hooks.ReviewTutor
}

// Interceptors returns the client interceptors.
func (c *ReviewTutorClient) Interceptors() []Interceptor {
	return c.inters.ReviewTutor
}

func (c *ReviewTutorClient) mutate(ctx context.Context, m *ReviewTutorMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ReviewTutorCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ReviewTutorUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ReviewTutorUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ReviewTutorDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown ReviewTutor mutation op: %q", m.Op())
	}
}

// ScheduleClient is a client for the Schedule schema.
type ScheduleClient struct {
	config
}

// NewScheduleClient returns a client for the Schedule from the given config.
func NewScheduleClient(c config) *ScheduleClient {
	return &ScheduleClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `schedule.Hooks(f(g(h())))`.
func (c *ScheduleClient) Use(hooks ...Hook) {
	c.hooks.Schedule = append(c.hooks.Schedule, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `schedule.Intercept(f(g(h())))`.
func (c *ScheduleClient) Intercept(interceptors ...Interceptor) {
	c.inters.Schedule = append(c.inters.Schedule, interceptors...)
}

// Create returns a builder for creating a Schedule entity.
func (c *ScheduleClient) Create() *ScheduleCreate {
	mutation := newScheduleMutation(c.config, OpCreate)
	return &ScheduleCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Schedule entities.
func (c *ScheduleClient) CreateBulk(builders ...*ScheduleCreate) *ScheduleCreateBulk {
	return &ScheduleCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Schedule.
func (c *ScheduleClient) Update() *ScheduleUpdate {
	mutation := newScheduleMutation(c.config, OpUpdate)
	return &ScheduleUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ScheduleClient) UpdateOne(s *Schedule) *ScheduleUpdateOne {
	mutation := newScheduleMutation(c.config, OpUpdateOne, withSchedule(s))
	return &ScheduleUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ScheduleClient) UpdateOneID(id uuid.UUID) *ScheduleUpdateOne {
	mutation := newScheduleMutation(c.config, OpUpdateOne, withScheduleID(id))
	return &ScheduleUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Schedule.
func (c *ScheduleClient) Delete() *ScheduleDelete {
	mutation := newScheduleMutation(c.config, OpDelete)
	return &ScheduleDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ScheduleClient) DeleteOne(s *Schedule) *ScheduleDeleteOne {
	return c.DeleteOneID(s.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ScheduleClient) DeleteOneID(id uuid.UUID) *ScheduleDeleteOne {
	builder := c.Delete().Where(schedule.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ScheduleDeleteOne{builder}
}

// Query returns a query builder for Schedule.
func (c *ScheduleClient) Query() *ScheduleQuery {
	return &ScheduleQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeSchedule},
		inters: c.Interceptors(),
	}
}

// Get returns a Schedule entity by its id.
func (c *ScheduleClient) Get(ctx context.Context, id uuid.UUID) (*Schedule, error) {
	return c.Query().Where(schedule.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ScheduleClient) GetX(ctx context.Context, id uuid.UUID) *Schedule {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryTutor queries the tutor edge of a Schedule.
func (c *ScheduleClient) QueryTutor(s *Schedule) *TutorQuery {
	query := (&TutorClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := s.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(schedule.Table, schedule.FieldID, id),
			sqlgraph.To(tutor.Table, tutor.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, schedule.TutorTable, schedule.TutorColumn),
		)
		fromV = sqlgraph.Neighbors(s.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryClass queries the class edge of a Schedule.
func (c *ScheduleClient) QueryClass(s *Schedule) *ClassQuery {
	query := (&ClassClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := s.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(schedule.Table, schedule.FieldID, id),
			sqlgraph.To(class.Table, class.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, schedule.ClassTable, schedule.ClassColumn),
		)
		fromV = sqlgraph.Neighbors(s.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *ScheduleClient) Hooks() []Hook {
	return c.hooks.Schedule
}

// Interceptors returns the client interceptors.
func (c *ScheduleClient) Interceptors() []Interceptor {
	return c.inters.Schedule
}

func (c *ScheduleClient) mutate(ctx context.Context, m *ScheduleMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ScheduleCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ScheduleUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ScheduleUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ScheduleDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Schedule mutation op: %q", m.Op())
	}
}

// StudentClient is a client for the Student schema.
type StudentClient struct {
	config
}

// NewStudentClient returns a client for the Student from the given config.
func NewStudentClient(c config) *StudentClient {
	return &StudentClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `student.Hooks(f(g(h())))`.
func (c *StudentClient) Use(hooks ...Hook) {
	c.hooks.Student = append(c.hooks.Student, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `student.Intercept(f(g(h())))`.
func (c *StudentClient) Intercept(interceptors ...Interceptor) {
	c.inters.Student = append(c.inters.Student, interceptors...)
}

// Create returns a builder for creating a Student entity.
func (c *StudentClient) Create() *StudentCreate {
	mutation := newStudentMutation(c.config, OpCreate)
	return &StudentCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Student entities.
func (c *StudentClient) CreateBulk(builders ...*StudentCreate) *StudentCreateBulk {
	return &StudentCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Student.
func (c *StudentClient) Update() *StudentUpdate {
	mutation := newStudentMutation(c.config, OpUpdate)
	return &StudentUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *StudentClient) UpdateOne(s *Student) *StudentUpdateOne {
	mutation := newStudentMutation(c.config, OpUpdateOne, withStudent(s))
	return &StudentUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *StudentClient) UpdateOneID(id uuid.UUID) *StudentUpdateOne {
	mutation := newStudentMutation(c.config, OpUpdateOne, withStudentID(id))
	return &StudentUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Student.
func (c *StudentClient) Delete() *StudentDelete {
	mutation := newStudentMutation(c.config, OpDelete)
	return &StudentDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *StudentClient) DeleteOne(s *Student) *StudentDeleteOne {
	return c.DeleteOneID(s.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *StudentClient) DeleteOneID(id uuid.UUID) *StudentDeleteOne {
	builder := c.Delete().Where(student.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &StudentDeleteOne{builder}
}

// Query returns a query builder for Student.
func (c *StudentClient) Query() *StudentQuery {
	return &StudentQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeStudent},
		inters: c.Interceptors(),
	}
}

// Get returns a Student entity by its id.
func (c *StudentClient) Get(ctx context.Context, id uuid.UUID) (*Student, error) {
	return c.Query().Where(student.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *StudentClient) GetX(ctx context.Context, id uuid.UUID) *Student {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryMatch queries the match edge of a Student.
func (c *StudentClient) QueryMatch(s *Student) *MatchQuery {
	query := (&MatchClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := s.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(student.Table, student.FieldID, id),
			sqlgraph.To(match.Table, match.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, student.MatchTable, student.MatchColumn),
		)
		fromV = sqlgraph.Neighbors(s.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryReviewCourse queries the review_course edge of a Student.
func (c *StudentClient) QueryReviewCourse(s *Student) *ReviewCourseQuery {
	query := (&ReviewCourseClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := s.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(student.Table, student.FieldID, id),
			sqlgraph.To(reviewcourse.Table, reviewcourse.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, student.ReviewCourseTable, student.ReviewCoursePrimaryKey...),
		)
		fromV = sqlgraph.Neighbors(s.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryReviewTutor queries the review_tutor edge of a Student.
func (c *StudentClient) QueryReviewTutor(s *Student) *ReviewTutorQuery {
	query := (&ReviewTutorClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := s.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(student.Table, student.FieldID, id),
			sqlgraph.To(reviewtutor.Table, reviewtutor.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, student.ReviewTutorTable, student.ReviewTutorPrimaryKey...),
		)
		fromV = sqlgraph.Neighbors(s.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryUser queries the user edge of a Student.
func (c *StudentClient) QueryUser(s *Student) *UserQuery {
	query := (&UserClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := s.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(student.Table, student.FieldID, id),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, student.UserTable, student.UserColumn),
		)
		fromV = sqlgraph.Neighbors(s.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *StudentClient) Hooks() []Hook {
	return c.hooks.Student
}

// Interceptors returns the client interceptors.
func (c *StudentClient) Interceptors() []Interceptor {
	return c.inters.Student
}

func (c *StudentClient) mutate(ctx context.Context, m *StudentMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&StudentCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&StudentUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&StudentUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&StudentDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Student mutation op: %q", m.Op())
	}
}

// TutorClient is a client for the Tutor schema.
type TutorClient struct {
	config
}

// NewTutorClient returns a client for the Tutor from the given config.
func NewTutorClient(c config) *TutorClient {
	return &TutorClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `tutor.Hooks(f(g(h())))`.
func (c *TutorClient) Use(hooks ...Hook) {
	c.hooks.Tutor = append(c.hooks.Tutor, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `tutor.Intercept(f(g(h())))`.
func (c *TutorClient) Intercept(interceptors ...Interceptor) {
	c.inters.Tutor = append(c.inters.Tutor, interceptors...)
}

// Create returns a builder for creating a Tutor entity.
func (c *TutorClient) Create() *TutorCreate {
	mutation := newTutorMutation(c.config, OpCreate)
	return &TutorCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Tutor entities.
func (c *TutorClient) CreateBulk(builders ...*TutorCreate) *TutorCreateBulk {
	return &TutorCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Tutor.
func (c *TutorClient) Update() *TutorUpdate {
	mutation := newTutorMutation(c.config, OpUpdate)
	return &TutorUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *TutorClient) UpdateOne(t *Tutor) *TutorUpdateOne {
	mutation := newTutorMutation(c.config, OpUpdateOne, withTutor(t))
	return &TutorUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *TutorClient) UpdateOneID(id uuid.UUID) *TutorUpdateOne {
	mutation := newTutorMutation(c.config, OpUpdateOne, withTutorID(id))
	return &TutorUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Tutor.
func (c *TutorClient) Delete() *TutorDelete {
	mutation := newTutorMutation(c.config, OpDelete)
	return &TutorDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *TutorClient) DeleteOne(t *Tutor) *TutorDeleteOne {
	return c.DeleteOneID(t.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *TutorClient) DeleteOneID(id uuid.UUID) *TutorDeleteOne {
	builder := c.Delete().Where(tutor.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &TutorDeleteOne{builder}
}

// Query returns a query builder for Tutor.
func (c *TutorClient) Query() *TutorQuery {
	return &TutorQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeTutor},
		inters: c.Interceptors(),
	}
}

// Get returns a Tutor entity by its id.
func (c *TutorClient) Get(ctx context.Context, id uuid.UUID) (*Tutor, error) {
	return c.Query().Where(tutor.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *TutorClient) GetX(ctx context.Context, id uuid.UUID) *Tutor {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryIssueReport queries the issue_report edge of a Tutor.
func (c *TutorClient) QueryIssueReport(t *Tutor) *IssueReportQuery {
	query := (&IssueReportClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := t.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(tutor.Table, tutor.FieldID, id),
			sqlgraph.To(issuereport.Table, issuereport.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, tutor.IssueReportTable, tutor.IssueReportColumn),
		)
		fromV = sqlgraph.Neighbors(t.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryCourse queries the course edge of a Tutor.
func (c *TutorClient) QueryCourse(t *Tutor) *CourseQuery {
	query := (&CourseClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := t.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(tutor.Table, tutor.FieldID, id),
			sqlgraph.To(course.Table, course.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, tutor.CourseTable, tutor.CourseColumn),
		)
		fromV = sqlgraph.Neighbors(t.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryReviewTutor queries the review_tutor edge of a Tutor.
func (c *TutorClient) QueryReviewTutor(t *Tutor) *ReviewTutorQuery {
	query := (&ReviewTutorClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := t.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(tutor.Table, tutor.FieldID, id),
			sqlgraph.To(reviewtutor.Table, reviewtutor.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, tutor.ReviewTutorTable, tutor.ReviewTutorPrimaryKey...),
		)
		fromV = sqlgraph.Neighbors(t.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryUser queries the user edge of a Tutor.
func (c *TutorClient) QueryUser(t *Tutor) *UserQuery {
	query := (&UserClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := t.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(tutor.Table, tutor.FieldID, id),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, tutor.UserTable, tutor.UserColumn),
		)
		fromV = sqlgraph.Neighbors(t.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QuerySchedule queries the schedule edge of a Tutor.
func (c *TutorClient) QuerySchedule(t *Tutor) *ScheduleQuery {
	query := (&ScheduleClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := t.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(tutor.Table, tutor.FieldID, id),
			sqlgraph.To(schedule.Table, schedule.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, tutor.ScheduleTable, tutor.ScheduleColumn),
		)
		fromV = sqlgraph.Neighbors(t.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *TutorClient) Hooks() []Hook {
	return c.hooks.Tutor
}

// Interceptors returns the client interceptors.
func (c *TutorClient) Interceptors() []Interceptor {
	return c.inters.Tutor
}

func (c *TutorClient) mutate(ctx context.Context, m *TutorMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&TutorCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&TutorUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&TutorUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&TutorDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Tutor mutation op: %q", m.Op())
	}
}

// UserClient is a client for the User schema.
type UserClient struct {
	config
}

// NewUserClient returns a client for the User from the given config.
func NewUserClient(c config) *UserClient {
	return &UserClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `user.Hooks(f(g(h())))`.
func (c *UserClient) Use(hooks ...Hook) {
	c.hooks.User = append(c.hooks.User, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `user.Intercept(f(g(h())))`.
func (c *UserClient) Intercept(interceptors ...Interceptor) {
	c.inters.User = append(c.inters.User, interceptors...)
}

// Create returns a builder for creating a User entity.
func (c *UserClient) Create() *UserCreate {
	mutation := newUserMutation(c.config, OpCreate)
	return &UserCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of User entities.
func (c *UserClient) CreateBulk(builders ...*UserCreate) *UserCreateBulk {
	return &UserCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for User.
func (c *UserClient) Update() *UserUpdate {
	mutation := newUserMutation(c.config, OpUpdate)
	return &UserUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *UserClient) UpdateOne(u *User) *UserUpdateOne {
	mutation := newUserMutation(c.config, OpUpdateOne, withUser(u))
	return &UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *UserClient) UpdateOneID(id uuid.UUID) *UserUpdateOne {
	mutation := newUserMutation(c.config, OpUpdateOne, withUserID(id))
	return &UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for User.
func (c *UserClient) Delete() *UserDelete {
	mutation := newUserMutation(c.config, OpDelete)
	return &UserDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *UserClient) DeleteOne(u *User) *UserDeleteOne {
	return c.DeleteOneID(u.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *UserClient) DeleteOneID(id uuid.UUID) *UserDeleteOne {
	builder := c.Delete().Where(user.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &UserDeleteOne{builder}
}

// Query returns a query builder for User.
func (c *UserClient) Query() *UserQuery {
	return &UserQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeUser},
		inters: c.Interceptors(),
	}
}

// Get returns a User entity by its id.
func (c *UserClient) Get(ctx context.Context, id uuid.UUID) (*User, error) {
	return c.Query().Where(user.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *UserClient) GetX(ctx context.Context, id uuid.UUID) *User {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryStudent queries the student edge of a User.
func (c *UserClient) QueryStudent(u *User) *StudentQuery {
	query := (&StudentClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := u.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(user.Table, user.FieldID, id),
			sqlgraph.To(student.Table, student.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, user.StudentTable, user.StudentColumn),
		)
		fromV = sqlgraph.Neighbors(u.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryTutor queries the tutor edge of a User.
func (c *UserClient) QueryTutor(u *User) *TutorQuery {
	query := (&TutorClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := u.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(user.Table, user.FieldID, id),
			sqlgraph.To(tutor.Table, tutor.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, user.TutorTable, user.TutorColumn),
		)
		fromV = sqlgraph.Neighbors(u.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryIssueReport queries the issue_report edge of a User.
func (c *UserClient) QueryIssueReport(u *User) *IssueReportQuery {
	query := (&IssueReportClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := u.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(user.Table, user.FieldID, id),
			sqlgraph.To(issuereport.Table, issuereport.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, user.IssueReportTable, user.IssueReportColumn),
		)
		fromV = sqlgraph.Neighbors(u.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryPayment queries the payment edge of a User.
func (c *UserClient) QueryPayment(u *User) *PaymentQuery {
	query := (&PaymentClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := u.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(user.Table, user.FieldID, id),
			sqlgraph.To(payment.Table, payment.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, user.PaymentTable, user.PaymentColumn),
		)
		fromV = sqlgraph.Neighbors(u.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryPaymentHistory queries the payment_history edge of a User.
func (c *UserClient) QueryPaymentHistory(u *User) *PaymentHistoryQuery {
	query := (&PaymentHistoryClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := u.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(user.Table, user.FieldID, id),
			sqlgraph.To(paymenthistory.Table, paymenthistory.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, user.PaymentHistoryTable, user.PaymentHistoryColumn),
		)
		fromV = sqlgraph.Neighbors(u.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryClassCancelRequest queries the class_cancel_request edge of a User.
func (c *UserClient) QueryClassCancelRequest(u *User) *ClassCancelRequestQuery {
	query := (&ClassCancelRequestClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := u.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(user.Table, user.FieldID, id),
			sqlgraph.To(classcancelrequest.Table, classcancelrequest.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, user.ClassCancelRequestTable, user.ClassCancelRequestColumn),
		)
		fromV = sqlgraph.Neighbors(u.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *UserClient) Hooks() []Hook {
	return c.hooks.User
}

// Interceptors returns the client interceptors.
func (c *UserClient) Interceptors() []Interceptor {
	return c.inters.User
}

func (c *UserClient) mutate(ctx context.Context, m *UserMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&UserCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&UserUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&UserDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown User mutation op: %q", m.Op())
	}
}
