// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/2110336-2565-2/Sec3-Group16-Tuder/ent/predicate"
	"github.com/2110336-2565-2/Sec3-Group16-Tuder/ent/reporttutor"
)

// ReportTutorDelete is the builder for deleting a ReportTutor entity.
type ReportTutorDelete struct {
	config
	hooks    []Hook
	mutation *ReportTutorMutation
}

// Where appends a list predicates to the ReportTutorDelete builder.
func (rtd *ReportTutorDelete) Where(ps ...predicate.ReportTutor) *ReportTutorDelete {
	rtd.mutation.Where(ps...)
	return rtd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (rtd *ReportTutorDelete) Exec(ctx context.Context) (int, error) {
	return withHooks[int, ReportTutorMutation](ctx, rtd.sqlExec, rtd.mutation, rtd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (rtd *ReportTutorDelete) ExecX(ctx context.Context) int {
	n, err := rtd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (rtd *ReportTutorDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(reporttutor.Table, sqlgraph.NewFieldSpec(reporttutor.FieldID, field.TypeInt))
	if ps := rtd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, rtd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	rtd.mutation.done = true
	return affected, err
}

// ReportTutorDeleteOne is the builder for deleting a single ReportTutor entity.
type ReportTutorDeleteOne struct {
	rtd *ReportTutorDelete
}

// Where appends a list predicates to the ReportTutorDelete builder.
func (rtdo *ReportTutorDeleteOne) Where(ps ...predicate.ReportTutor) *ReportTutorDeleteOne {
	rtdo.rtd.mutation.Where(ps...)
	return rtdo
}

// Exec executes the deletion query.
func (rtdo *ReportTutorDeleteOne) Exec(ctx context.Context) error {
	n, err := rtdo.rtd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{reporttutor.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (rtdo *ReportTutorDeleteOne) ExecX(ctx context.Context) {
	if err := rtdo.Exec(ctx); err != nil {
		panic(err)
	}
}
